function lambda=get_lambda_using_ci(a,D,a2,ca,ci,cp)
% quadratic eq, the nonlinear appraoch
%% lambda solved from g
% l1 = 0;
% l2 = (K + ca)./(D.*a);
% l3 = (K.*Vcmax - Vcmax.*ca + K.^2.*g_c + ca.^2.*g_c + 2.*Gamma_star.*Vcmax + K.*Vcmax.^2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + Vcmax.^2.*ca.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 2.*K.*ca.*g_c + K.^3.*g_c.^2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + ca.^3.*g_c.^2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 2.*K.^2.*Vcmax.*g_c.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) - 2.*Vcmax.*ca.^2.*g_c.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 3.*K.*ca.^2.*g_c.^2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 3.*K.^2.*ca.*g_c.^2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 4.*Gamma_star.*K.*Vcmax.*g_c.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 4.*Gamma_star.*Vcmax.*ca.*g_c.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2))./(2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2).*(a.*D.*K.^2.*g_c.^2 + 2.*a.*D.*K.*Vcmax.*g_c + 2.*a.*D.*K.*ca.*g_c.^2 + a.*D.*Vcmax.^2 - 2.*a.*D.*Vcmax.*ca.*g_c + 4.*Gamma_star.*a.*D.*Vcmax.*g_c + a.*D.*ca.^2.*g_c.^2));
% l4 = (Vcmax.*ca - K.*Vcmax - K.^2.*g_c - ca.^2.*g_c - 2.*Gamma_star.*Vcmax + K.*Vcmax.^2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + Vcmax.^2.*ca.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) - 2.*K.*ca.*g_c + K.^3.*g_c.^2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + ca.^3.*g_c.^2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 2.*K.^2.*Vcmax.*g_c.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) - 2.*Vcmax.*ca.^2.*g_c.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 3.*K.*ca.^2.*g_c.^2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 3.*K.^2.*ca.*g_c.^2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 4.*Gamma_star.*K.*Vcmax.*g_c.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2) + 4.*Gamma_star.*Vcmax.*ca.*g_c.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2))./(2.*(1./(K.^2.*g_c.^2 + 2.*K.*Vcmax.*g_c + 2.*K.*ca.*g_c.^2 + Vcmax.^2 - 2.*Vcmax.*ca.*g_c + 4.*Gamma_star.*Vcmax.*g_c + ca.^2.*g_c.^2)).^(1./2).*(a.*D.*K.^2.*g_c.^2 + 2.*a.*D.*K.*Vcmax.*g_c + 2.*a.*D.*K.*ca.*g_c.^2 + a.*D.*Vcmax.^2 - 2.*a.*D.*Vcmax.*ca.*g_c + 4.*Gamma_star.*a.*D.*Vcmax.*g_c + a.*D.*ca.^2.*g_c.^2));

Gamma_star = cp;
ci_c = ci;
K = a2;

%% lambda solved from ci
lambda.l1 = (Gamma_star.*ca.^2 + Gamma_star.*ci_c.^2 + K.*ca.^2 + K.*ci_c.^2 - 2.*Gamma_star.*ca.*ci_c - 2.*K.*ca.*ci_c)./(a.*D.*ci_c.^2 - 2.*Gamma_star.*a.*D.*ci_c - Gamma_star.*K.*a.*D + Gamma_star.*a.*ca.*D + K.*a.*ca.*D);
lambda.l2 = -(Gamma_star.*K.^2 + Gamma_star.*ci_c.^2 - K.^2.*ca - ca.*ci_c.^2 + 2.*Gamma_star.*K.*ci_c - 2.*K.*ca.*ci_c)./(a.*D.*ci_c.^2 - 2.*Gamma_star.*a.*D.*ci_c - Gamma_star.*K.*a.*D + Gamma_star.*a.*ca.*D + K.*a.*ca.*D);
%lambda.l3 = (Gamma_star + K)./(D.*a);
%lambda.l4 = -(Gamma_star - ca)./(D.*a);
check=1;
end